/*DROP DATABASE DiagonAlley;*/
CREATE DATABASE DiagonAlley;
USE DiagonAlley;

/* Admin user TABLE */
CREATE TABLE adminUser(
	userEmail VARCHAR(100) NOT NULL,
	userName VARCHAR(50) NOT NULL,
	password VARCHAR(50) NOT NULL,
	userType INT NOT NULL DEFAULT 0,
	status INT NOT NULL DEFAULT 0,
	CONSTRAINT PRIMARY KEY(userEmail)
);

/* Category TABLE */
CREATE TABLE category(
	catID INT AUTO_INCREMENT NOT NULL,
	catName VARCHAR(100) NOT NULL,
	CONSTRAINT PRIMARY KEY(catID)
);

/* book TABLE */
CREATE TABLE book(
	bookID INT AUTO_INCREMENT NOT NULL,
	catID INT NOT NULL,
	name VARCHAR(150) NOT NULL,
	edition VARCHAR(100) NOT NULL,
	publishDate DATE NOT NULL,
	CONSTRAINT PRIMARY KEY(bookID),
	CONSTRAINT FOREIGN KEY(catID) REFERENCES category(catID)
	ON DELETE CASCADE ON UPDATE CASCADE
);

/* publishDetails TABLE */
CREATE TABLE publishDetails(
	bookID INT NOT NULL,
	userEmail VARCHAR(100) NOT NULL,
	CONSTRAINT PRIMARY KEY(bookID,userEmail),
    CONSTRAINT FOREIGN KEY(bookID) REFERENCES book(bookID)
    ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT FOREIGN KEY(userEmail) REFERENCES adminUser(userEmail)
    ON DELETE CASCADE ON UPDATE CASCADE
);

/* author TABLE */
CREATE TABLE author(
	authorID INT AUTO_INCREMENT NOT NULL,
	AuthorName VARCHAR(150) NOT NULL,
	CONSTRAINT PRIMARY KEY(authorID)
);

/* feedBack TABLE */
CREATE TABLE feedBack(
	bookID INT NOT NULL,
	authorID INT NOT NULL,
	comments VARCHAR(225) NOT NULL,
	createdDate DATE NOT NULL,
	createdTime TIME NOT NULL,
	CONSTRAINT PRIMARY KEY(bookID,authorID),
    CONSTRAINT FOREIGN KEY(bookID) REFERENCES book(bookID)
    ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT FOREIGN KEY(authorID) REFERENCES author(authorID)
    ON DELETE CASCADE ON UPDATE CASCADE
);
